FROM python:3.9-slim

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Instalar psycopg2
RUN pip install psycopg2-binary

# Copiar scripts
COPY scripts/ /scripts/
COPY sql/ /sql/

WORKDIR /scripts

# Hacer scripts ejecutables
RUN chmod +x *.py

CMD ["python3", "load_data.py"]
